language: python

python:
    - "2.7"
    - "3.4"


env:
    - FLASK_PROFILER_TEST_CONF=sqlite
    - FLASK_PROFILER_TEST_CONF=mongodb
    - FLASK_PROFILER_TEST_CONF=sqlalchemy

install:
    - pip install flask
    - pip install flask-testing
    - pip install pymongo
    - pip install coveralls
    - pip install sqlalchemy
    - pip install configparser

services:
    - mongodb
    - mysql

before_install:
  - mysql -e 'CREATE DATABASE flask_profiler;'

script: python setup.py test
